const express = require('express');
const router = express.Router();
const enrollCtrl = require('../controllers/enrollment.controller');
const verifyToken = require('../middleware/verifyToken');
const requireRole = require('../middleware/requireRole');
router.use(verifyToken);
router.get('/', enrollCtrl.list);
router.get('/my', requireRole('student'), enrollCtrl.myEnrollments);
router.post('/', requireRole('admin'), enrollCtrl.create);
router.put('/:id', requireRole('admin'), enrollCtrl.update);
router.delete('/:id', requireRole('admin'), enrollCtrl.remove);
module.exports = router;
